name: vaccination_tracker
description: "Vaccination tracker helps to track children's vaccination."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  sqflite_common_ffi_web: ^0.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4


flutter:
  assets:
    - assets/vaccinationImg.webp

 
  uses-material-design: true
